# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: adityaexp
# "service" is the name of this project. This will also be added to your AWS resource names.
service: exploring-serverless

provider:
  name: aws
  runtime: nodejs20.x
  # Uncomment to easily set up a custom domain. Read the docs for more details:
  # https://www.serverless.com/framework/docs/providers/aws/guide/domains
  # domain: api.example.com
  region: ap-south-1

functions:
  firstFnLambda:
    handler: firstFn.handler
    events:
      - httpApi:
          path: /firstFn
          method: get
  secondFnLambda:
    handler: secondFn.handler
    events:
      - httpApi:
          path: /secondFn
          method: get